from distutils.core import setup
setup(
  name = 'tksheet',
  packages = ['tksheet',
              'tksheet._tksheet_column_headers',
              'tksheet._tksheet_main_table',
              'tksheet._tksheet_other_classes',
              'tksheet._tksheet_row_index',
              'tksheet._tksheet_top_left_rectangle',
              'tksheet._tksheet_vars'],
  version = '3.1',
  license='MIT',
  description = 'Tkinter table / sheet widget',
  author = 'ragardner',
  author_email = 'ragardner@protonmail.com',
  url = 'https://github.com/ragardner/tksheet',
  download_url = 'https://github.com/ragardner/tksheet/archive/3.1.tar.gz',
  keywords = ['tkinter', 'table', 'widget'],
  install_requires=[],
  classifiers=[
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.7',
  ],
)
